# Generated by Django 5.2.7 on 2025-10-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='전략명')),
                ('strategy_type', models.CharField(choices=[('ma_cross', '이동평균 크로스오버'), ('rsi', 'RSI 전략'), ('bollinger', '볼린저밴드'), ('momentum', '모멘텀'), ('mean_reversion', '평균회귀'), ('custom', '커스텀')], max_length=50, verbose_name='전략 유형')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('parameters', models.JSONField(default=dict, verbose_name='파라미터')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '전략',
                'verbose_name_plural': '전략',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('total_return', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='총 수익률(%)')),
                ('annual_return', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='연 수익률(%)')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='샤프 비율')),
                ('max_drawdown', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='최대 낙폭(%)')),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='승률(%)')),
                ('total_trades', models.IntegerField(default=0, verbose_name='총 거래 횟수')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=10000000, max_digits=15, verbose_name='초기 자본금')),
                ('final_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='최종 자본금')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('kr_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.companyinfo', verbose_name='한국 종목')),
                ('us_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.uscompanyinfo', verbose_name='미국 종목')),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quant.strategy', verbose_name='전략')),
            ],
            options={
                'verbose_name': '백테스트',
                'verbose_name_plural': '백테스트',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='신호 발생일')),
                ('signal_type', models.CharField(choices=[('buy', '매수'), ('sell', '매도')], max_length=10, verbose_name='신호 유형')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='가격')),
                ('quantity', models.IntegerField(default=0, verbose_name='수량')),
                ('reason', models.TextField(blank=True, verbose_name='신호 발생 이유')),
                ('indicator_values', models.JSONField(default=dict, verbose_name='지표값')),
                ('backtest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='quant.backtest', verbose_name='백테스트')),
            ],
            options={
                'verbose_name': '거래 신호',
                'verbose_name_plural': '거래 신호',
                'ordering': ['date'],
            },
        ),
    ]
