# Generated by Django 5.2.7 on 2025-12-02 05:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간')], max_length=10)),
                ('market', models.CharField(choices=[('kr', '한국'), ('us', '미국'), ('all', '전체')], default='all', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_time', models.TimeField(help_text='보고서 생성 시간')),
                ('send_email', models.BooleanField(default=False)),
                ('email_recipients', models.JSONField(blank=True, default=list)),
                ('last_generated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['report_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', '일간'), ('weekly', '주간'), ('monthly', '월간')], default='daily', max_length=10)),
                ('market', models.CharField(choices=[('kr', '한국'), ('us', '미국'), ('all', '전체')], default='all', max_length=5)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('market_indices', models.JSONField(blank=True, default=dict)),
                ('sector_analysis', models.JSONField(blank=True, default=dict)),
                ('top_volume_stocks', models.JSONField(blank=True, default=list)),
                ('top_gainers', models.JSONField(blank=True, default=list)),
                ('top_losers', models.JSONField(blank=True, default=list)),
                ('technical_summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
                'indexes': [models.Index(fields=['-report_date'], name='reports_mar_report__028973_idx'), models.Index(fields=['report_type', 'market'], name='reports_mar_report__0978f1_idx')],
                'unique_together': {('report_type', 'market', 'report_date')},
            },
        ),
    ]
