# Generated by Django 5.2.7 on 2025-10-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=50, unique=True)),
                ('index_name', models.CharField(max_length=100)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('change_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('change_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시장 지수',
                'verbose_name_plural': '시장 지수',
                'db_table': 'market_index',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '회사 정보',
                'verbose_name_plural': '회사 정보',
                'db_table': 'company_info',
                'indexes': [models.Index(fields=['company_name'], name='company_inf_company_4a4f68_idx'), models.Index(fields=['company_code'], name='company_inf_company_33cb25_idx'), models.Index(fields=['is_active'], name='company_inf_is_acti_52ee18_idx')],
            },
        ),
        migrations.CreateModel(
            name='USCompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, help_text='티커 심볼 (예: AAPL)', max_length=10, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('exchange', models.CharField(blank=True, help_text='NASDAQ, NYSE 등', max_length=20, null=True)),
                ('country', models.CharField(default='US', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'US Company Info',
                'verbose_name_plural': 'US Company Infos',
                'indexes': [models.Index(fields=['symbol'], name='stocks_usco_symbol_f23eba_idx'), models.Index(fields=['company_name'], name='stocks_usco_company_a6898b_idx'), models.Index(fields=['is_active'], name='stocks_usco_is_acti_684494_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.companyinfo')),
            ],
            options={
                'verbose_name': '주가 데이터',
                'verbose_name_plural': '주가 데이터',
                'db_table': 'price_data',
                'indexes': [models.Index(fields=['stock', 'date'], name='price_data_stock_i_60ba52_idx'), models.Index(fields=['date'], name='price_data_date_bc33aa_idx'), models.Index(fields=['stock', '-date'], name='price_data_stock_i_8c5056_idx')],
                'unique_together': {('stock', 'date')},
            },
        ),
        migrations.CreateModel(
            name='USPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('adj_close_price', models.DecimalField(blank=True, decimal_places=4, help_text='배당/분할 조정 종가', max_digits=12, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='stocks.uscompanyinfo')),
            ],
            options={
                'verbose_name': 'US Price Data',
                'verbose_name_plural': 'US Price Data',
                'indexes': [models.Index(fields=['stock', 'date'], name='stocks_uspr_stock_i_8ec1ff_idx'), models.Index(fields=['symbol', 'date'], name='stocks_uspr_symbol_6877d9_idx'), models.Index(fields=['date'], name='stocks_uspr_date_43a422_idx'), models.Index(fields=['stock', '-date'], name='stocks_uspr_stock_i_48648e_idx')],
                'constraints': [models.UniqueConstraint(fields=('stock', 'date'), name='uniq_us_stock_date')],
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.companyinfo')),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목',
                'db_table': 'watch_list',
                'unique_together': {('user_session', 'company')},
            },
        ),
    ]
