# Generated by Django 5.2.7 on 2025-10-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='listing_date',
            field=models.DateField(blank=True, help_text='상장일', null=True),
        ),
    ]
